import Head from 'next/head'
import Link from 'next/link'
import { Container } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cipher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="main">
        <h1 className="title">
          cipher
        </h1>
        <Link href="/vigenere">
          <h2>
            Vigenere Cipher
          </h2>
        </Link>
      </Container>
    </>
  )
}