import Head from "next/head";
import Link from "next/link";
import { Container, Typography } from "@mui/material";

export default function Home() {
  const childSx = {
    fontSize: "1.25em",
    marginBottom: "0.25em",
    "&:hover": {
      color: "primary.main",
    },
  };
  return (
    <>
      <Head>
        <title>Cipher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="main">
        <Typography
          sx={{
            fontSize: "2rem",
            fontWeight: "bold",
            marginY: "1rem",
          }}
        >
          Cryptography - Classical Ciphers
        </Typography>
        <Link href="/vigenere">
          <Typography sx={childSx}>Vigenere Cipher</Typography>
        </Link>
        <Link href="/affine">
          <Typography sx={childSx}>Affine Cipher</Typography>
        </Link>
        <Link href="/hill">
          <Typography sx={childSx}>Hill Cipher</Typography>
        </Link>
        <Link href="/playfair">
          <Typography sx={childSx}>Playfair Cipher</Typography>
        </Link>
      </Container>
    </>
  );
}
